{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore","doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError","doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/LocalizedError-Implementations"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"errorDescription","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/cloudxcore\/cloudxerror\/errordescription"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","metadata":{"modules":[{"name":"CloudXCore"}],"roleHeading":"Instance Property","symbolKind":"property","externalID":"s:10CloudXCore0A6XErrorO16errorDescriptionSSSgvp","extendedModule":"CloudXCore","title":"errorDescription","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"abstract":[{"type":"text","text":"A localized message describing what error occurred."}],"identifier":{"url":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/errorDescription","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.cloudx.sdk.core/documentation/CloudXCore":{"role":"collection","kind":"symbol","title":"CloudXCore","type":"topic","identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore","abstract":[],"url":"\/documentation\/cloudxcore"},"doc://com.cloudx.sdk.core/documentation/CloudXCore/CloudXError/LocalizedError-Implementations":{"role":"collectionGroup","title":"LocalizedError Implementations","kind":"article","type":"topic","identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/LocalizedError-Implementations","abstract":[],"url":"\/documentation\/cloudxcore\/cloudxerror\/localizederror-implementations"},"doc://com.cloudx.sdk.core/documentation/CloudXCore/CloudXError/errorDescription":{"role":"symbol","identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/errorDescription","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"url":"\/documentation\/cloudxcore\/cloudxerror\/errordescription","title":"errorDescription","abstract":[{"type":"text","text":"A localized message describing what error occurred."}],"kind":"symbol","type":"topic"},"doc://com.cloudx.sdk.core/documentation/CloudXCore/CloudXError":{"title":"CloudXError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"CloudXError","kind":"identifier"}],"identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError","url":"\/documentation\/cloudxcore\/cloudxerror","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"CloudXError","kind":"identifier"}],"abstract":[{"type":"text","text":"An error type that represents the CloudX SDK errors."}]}}}