{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/generalAdError"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"General ad error."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"generalAdError","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"generalAdError"}],"externalID":"s:10CloudXCore0A6XErrorO14generalAdErroryA2CmF","role":"symbol","modules":[{"name":"CloudXCore"}],"symbolKind":"case","title":"CloudXError.generalAdError","roleHeading":"Case"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore","doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError"]]},"variants":[{"paths":["\/documentation\/cloudxcore\/cloudxerror\/generaladerror"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.cloudx.sdk.core/documentation/CloudXCore":{"type":"topic","abstract":[],"title":"CloudXCore","role":"collection","kind":"symbol","identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore","url":"\/documentation\/cloudxcore"},"doc://com.cloudx.sdk.core/documentation/CloudXCore/CloudXError":{"url":"\/documentation\/cloudxcore\/cloudxerror","role":"symbol","kind":"symbol","title":"CloudXError","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CloudXError","kind":"identifier"}],"type":"topic","abstract":[{"text":"An error type that represents the CloudX SDK errors.","type":"text"}],"navigatorTitle":[{"text":"CloudXError","kind":"identifier"}],"identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError"},"doc://com.cloudx.sdk.core/documentation/CloudXCore/CloudXError/generalAdError":{"identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/generalAdError","type":"topic","abstract":[{"type":"text","text":"General ad error."}],"title":"CloudXError.generalAdError","url":"\/documentation\/cloudxcore\/cloudxerror\/generaladerror","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"generalAdError"}],"kind":"symbol"}}}