{"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore","doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError"]]},"identifier":{"url":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/generalAdError","interfaceLanguage":"swift"},"metadata":{"symbolKind":"case","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"generalAdError","kind":"identifier"}],"externalID":"s:10CloudXCore0A6XErrorO14generalAdErroryA2CmF","modules":[{"name":"CloudXCore"}],"title":"CloudXError.generalAdError","role":"symbol"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"generalAdError","kind":"identifier"}]}],"kind":"declarations"}],"abstract":[{"text":"General ad error.","type":"text"}],"variants":[{"paths":["\/documentation\/cloudxcore\/cloudxerror\/generaladerror"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.cloudx.sdk.core/documentation/CloudXCore/CloudXError":{"type":"topic","title":"CloudXError","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CloudXError"}],"navigatorTitle":[{"kind":"identifier","text":"CloudXError"}],"url":"\/documentation\/cloudxcore\/cloudxerror","abstract":[{"type":"text","text":"An error type that represents the CloudX SDK errors."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError"},"doc://com.cloudx.sdk.core/documentation/CloudXCore":{"abstract":[],"type":"topic","url":"\/documentation\/cloudxcore","title":"CloudXCore","kind":"symbol","identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore","role":"collection"},"doc://com.cloudx.sdk.core/documentation/CloudXCore/CloudXError/generalAdError":{"type":"topic","abstract":[{"type":"text","text":"General ad error."}],"role":"symbol","kind":"symbol","title":"CloudXError.generalAdError","identifier":"doc:\/\/com.cloudx.sdk.core\/documentation\/CloudXCore\/CloudXError\/generalAdError","url":"\/documentation\/cloudxcore\/cloudxerror\/generaladerror","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"generalAdError","kind":"identifier"}]}}}